const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("nimbo", {
  onHook: (fn) => ipcRenderer.on("hook", (_e, p) => fn(p)),
  onCursor: (fn) => ipcRenderer.on("cursor", (_e, p) => fn(p)),
  onMuted: (fn) => ipcRenderer.on("muted", (_e, m) => fn(m)),
  onPermission: (fn) => ipcRenderer.on("permission", (_e, p) => fn(p)),
  onPermissionDone: (fn) => ipcRenderer.on("permission-done", () => fn()),
  decide: (decision, rid) => ipcRenderer.send("decision", decision, rid),
  onMini: (fn) => ipcRenderer.on("mini", (_e, m) => fn(m)),
  toggleMini: () => ipcRenderer.send("toggle-mini"),
  chatOpen: (open) => ipcRenderer.send("chat-open", open),
  ask: (msg) => ipcRenderer.invoke("ask", msg),
  dispatch: (id, prompt) => ipcRenderer.invoke("dispatch", id, prompt),
  onTheme: (fn) => ipcRenderer.on("theme", (_e, t) => fn(t)),
  onGithub: (fn) => ipcRenderer.on("github", (_e, list) => fn(list)),
  openGithub: () => ipcRenderer.send("open-github"),
  openUrl: (url) => ipcRenderer.send("open-url", url),
  setup: () => ipcRenderer.invoke("setup"),
  setupDo: (action, value) => ipcRenderer.invoke("setup-do", action, value),
  onSetupOpen: (fn) => ipcRenderer.on("setup-open", () => fn()),
  onName: (fn) => ipcRenderer.on("name", (_e, n) => fn(n)),
  onAnchor: (fn) => ipcRenderer.on("anchor", (_e, f) => fn(f)),
  dragStart: (d) => ipcRenderer.send("drag-start", d),
  dragEnd: () => ipcRenderer.send("drag-end"),
  onDragAbort: (fn) => ipcRenderer.on("drag-abort", () => fn()),
  onWhatsapp: (fn) => ipcRenderer.on("whatsapp", (_e, d, alert) => fn(d, alert)),
  openWhatsapp: () => ipcRenderer.send("open-whatsapp"),
  whatsappRefresh: () => ipcRenderer.send("whatsapp-refresh"),
  whatsappDismiss: () => ipcRenderer.send("whatsapp-dismiss"),
  copy: (text) => ipcRenderer.send("copy", text),
  tts: (text) => ipcRenderer.invoke("tts", text),
  onVoice: (fn) => ipcRenderer.on("voice", (_e, on) => fn(on)),
  trello: () => ipcRenderer.invoke("trello"),
  onTrello: (fn) => ipcRenderer.on("trello", (_e, d) => fn(d)),
  onTrelloBusy: (fn) => ipcRenderer.on("trello-busy", (_e, b) => fn(b)),
  trelloRefresh: () => ipcRenderer.send("trello-refresh"),
  reminders: () => ipcRenderer.invoke("reminders"),
  onReminders: (fn) => ipcRenderer.on("reminders", (_e, list) => fn(list)),
  onReminder: (fn) => ipcRenderer.on("reminder", (_e, r) => fn(r)),
  reminderDone: (id) => ipcRenderer.send("reminder-done", id),
  reminderSnooze: (id, min) => ipcRenderer.send("reminder-snooze", id, min),
  // Ruta real de un archivo soltado o elegido (las imágenes pegadas no tienen: devuelve "").
  filePath: (file) => webUtils.getPathForFile(file),
  hitRects: (rects) => ipcRenderer.send("hit-rects", rects),
  onHover: (fn) => ipcRenderer.on("hover", (_e, on) => fn(on)),
  menu: () => ipcRenderer.send("menu"),
});
